#!/bin/bash
#
# check_pg_compat.sh — PG15/16/17/18 syntax-only compatibility gate for
# the duckdb_fdw C sources.
#
# Usage:
#   scripts/check_pg_compat.sh            # check all of 15 16 17 18
#   scripts/check_pg_compat.sh 15 18      # check only the listed versions
#
# What it does, per requested PG major version V:
#   1. Resolves a header tree for V:
#        a. /tmp/pg${V}_include              (hand-prepared tree, if present)
#        b. a locally installed server tree (pg_config / pg_config-${V}
#           whose major version matches V — a complete, authoritative set)
#        c. auto-setup: downloads the official source tarball from
#           ftp.postgresql.org and assembles a syntax-check tree (src/include
#           plus stubs for the build-generated headers: pg_config.h,
#           pg_config_os.h, pg_config_ext.h, utils/errcodes.h,
#           utils/fmgroids.h, utils/fmgrprotos.h, nodes/nodetags.h,
#           storage/lwlocknames.h, catalog/pg_*_d.h, catalog/syscache_ids.h).
#           _d.h / fmgroids stubs are borrowed from any locally installed PG
#           tree when available (see FDW_PG_STUB_SRC below).
#   2. Runs:  gcc -fsyntax-only -I <include tree> -I <repo root> <file>.c
#      for every C file in the Makefile OBJS list.
#
# Environment overrides:
#   FDW_PG_CACHE      cache dir for downloaded tarballs (default /tmp/fdw_pg_compat)
#   FDW_PG15_TARBALL  e.g. 15.10 (default: per-version table below)
#   FDW_PG16_TARBALL  e.g. 16.6
#   FDW_PG18_TARBALL  e.g. 18.0
#   FDW_PG_STUB_SRC   installed PG server include dir used to borrow the
#                     generated _d.h / fmgroids.h stubs
#                     (default: pg_config --includedir-server, if any)
#   FDW_CC            compiler (default: gcc)
#
# The syntax-only check cannot catch link-time or semantic issues; it is the
# cheap gate that reproduces the CI "expected 10 have 11" class of failures
# (changed planner API signatures, moved structs/headers) in seconds.

set -u

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
CC=${FDW_CC:-gcc}
CACHE=${FDW_PG_CACHE:-/tmp/fdw_pg_compat}
STUB_SRC=${FDW_PG_STUB_SRC:-$(pg_config --includedir-server 2>/dev/null || true)}

# C sources matching the Makefile OBJS list (OBJS = *.o of these).
SOURCES="connection.c option.c deparse.c duckdb_fdw.c import.c sql_utils.c runtime_guard.c"

# Default tarball versions (bump when you need a newer patch release; the
# signatures checked here are stable within a major version).
TARBALL_VERSION() {
    case "$1" in
        15) echo "${FDW_PG15_TARBALL:-15.10}" ;;
        16) echo "${FDW_PG16_TARBALL:-16.6}" ;;
        17) echo "${FDW_PG17_TARBALL:-17.9}" ;;
        18) echo "${FDW_PG18_TARBALL:-18.0}" ;;
        *)  return 1 ;;
    esac
}

# Minimal pg_config.h for the auto-setup path (glibc Linux only).  A
# machine with a local PG install skips this entirely (path b above).
write_minimal_pg_config() { # $1=dir $2=major $3=full $4=num
    cat > "$1/pg_config.h" <<EOF
/* syntax-check stub generated by scripts/check_pg_compat.sh */
#define PACKAGE_NAME "PostgreSQL"
#define PACKAGE_STRING "PostgreSQL $3"
#define PACKAGE_VERSION "$3"
#define VERSION "$3"
#define PG_VERSION "$3"
#define PG_VERSION_NUM $4
#define PG_VERSION_STR "PostgreSQL $3 (syntax-check stub)"
#define PG_MAJORVERSION "$2"
#define DEF_PGPORT 5432
#define DEF_PGPORT_STR "5432"
#define DLSUFFIX ".so"
#define BLCKSZ 8192
#define MAXIMUM_ALIGNOF 8
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_OFF_T 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_VOID_P 8
#define BLOCK_SIZE 8192
#define RELCACHE_INITSIZE 128
#define XLOG_BLCKSZ 8192
#define INDEX_MAX_KEYS 32
#define FLOAT8byVAL 1
#define INT64byVAL 1
#define HAVE_LONG_INT 1
#define HAVE_LONG_INT_64 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_UNNAMED_UNION_MEMBER 1
#define HAVE_DECL_SNPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDARG_PROTOTYPES 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_LIMITS_H 1
#define HAVE_FLOAT_H 1
#define HAVE_ISNAN 1
#define HAVE_ISINF 1
#define HAVE_FINITE 1
#define HAVE_STRERROR_R 1
#define SIZEOF_STRERROR_R 0
#define HAVE_BZERO 1
#define HAVE_MEMMOVE 1
#define HAVE_GETUID 1
#define HAVE_LOCALECONV 1
#define ENABLE_NLS 0
#define WITH_LLVM 0
#define HAVE_LIBZ 1
#define HAVE_ICONV 1
#define HAVE_MKSTEMP 1
#define HAVE_RANDOM 1
#define HAVE_SETENV 1
#define HAVE_SNPRINTF 1
#define HAVE_FDATASYNC 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE_PIPE2 1
#define HAVE_POLL 1
#define HAVE_FLOCK 1
#define HAVE_TIMESPEC 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_WAIT_H 1
EOF
}

# Build a syntax-check tree for version $1 under $2 (include dir).
setup_tarball_tree() {
    local V=$1 DIR=$2 TV
    TV=$(TARBALL_VERSION "$V") || { echo "unsupported version: $V" >&2; return 1; }
    local URL="https://ftp.postgresql.org/pub/source/v${TV}/postgresql-${TV}.tar.bz2"
    local TAR="$CACHE/postgresql-${TV}.tar.bz2"
    mkdir -p "$CACHE"
    if [ ! -f "$TAR" ]; then
        echo "  downloading $URL"
        curl -fsSL -m 600 -o "$TAR" "$URL" || { echo "  download failed: $URL" >&2; return 1; }
    fi
    rm -rf "$DIR" "$CACHE/extract-${TV}"
    mkdir -p "$DIR"
    tar xjf "$TAR" -C "$CACHE"
    cp -r "$CACHE/postgresql-${TV}/src/include/." "$DIR/"
    rm -rf "$CACHE/postgresql-${TV}"

    # --- stubs for headers that are generated at PG build time ---
    # pg_config.h: prefer a version-bumped copy of a local install's
    # pg_config.h (richest set of HAVE_*); else the built-in minimal one.
    if [ -n "${STUB_SRC:-}" ] && [ -f "$STUB_SRC/pg_config.h" ]; then
        sed -e "s/#define PG_VERSION_NUM [0-9]*/#define PG_VERSION_NUM $(pgnum $V)/" \
            -e "s/#define PG_VERSION \"[^\"]*\"/#define PG_VERSION \"${TV}\"/" \
            -e "s/#define PG_MAJORVERSION \"[0-9]*\"/#define PG_MAJORVERSION \"${V}\"/" \
            -e "s/#define PG_VERSION_STR .*//" \
            "$STUB_SRC/pg_config.h" > "$DIR/pg_config.h"
        echo "#define PG_VERSION_STR \"PostgreSQL ${TV} (syntax-check stub)\"" >> "$DIR/pg_config.h"
    else
        write_minimal_pg_config "$DIR" "$V" "$TV" "$(pgnum $V)"
    fi
    [ -f "$DIR/pg_config_os.h" ] || {
        # configure creates this from port/pg_config_<os>.h; for Linux:
        cp "$STUB_SRC/pg_config_os.h" "$DIR/" 2>/dev/null \
            || printf '/* stub */\n#include "port/linux.h"\n' > "$DIR/pg_config_os.h"
    }
    if [ -f "$STUB_SRC/pg_config_ext.h" ]; then
        cp "$STUB_SRC/pg_config_ext.h" "$DIR/"
    else
        cat > "$DIR/pg_config_ext.h" <<'EOF'
/* stub */
#define PG_INT64_TYPE int64
#define PG_INT64_FORMAT_PRIdINT64 "ld"
#define PG_INT64_FORMAT_PRIuINT64 "lu"
#define PG_INT64_FORMAT_SCNdINT64 "l"
#define PG_INT64_FORMAT_PRIxINT64 "lx"
#define PG_INT64_FORMAT_SCNxINT64 "l"
#define PG_INT64_TYPE int64
EOF
    fi

    local TB="$CACHE/postgresql-${TV}"   # gone; pieces re-extracted on demand
    # errcodes.h — generate from the source errcodes.txt
    tar xjf "$TAR" -C "$CACHE" --wildcards "*/src/backend/utils/errcodes.txt" 2>/dev/null
    local ECT="$(find "$CACHE" -name errcodes.txt -path "*${TV}*" | head -1)"
    if [ -n "${ECT:-}" ]; then
        python3 - "$ECT" "$DIR/utils/errcodes.h" <<'PYEOF'
import sys, re
src, dst = sys.argv[1], sys.argv[2]
out = ['/* syntax-check stub generated from errcodes.txt */',
       '/* Like the real file, this has deliberately no #include guard; */',
       '/* MAKE_SQLSTATE is defined by utils/elog.h before it includes us. */']
for line in open(src, encoding='utf-8'):
    line = line.strip()
    if not line or line.startswith('#') or line.startswith('Section:'):
        continue
    m = re.match(r'^([0-9A-Z]{5})\s+([EWS])\s+([A-Z][A-Z0-9_]*)\b', line)
    if m:
        s = m.group(1).upper()
        out.append('#define %s MAKE_SQLSTATE(\'%s\',\'%s\',\'%s\',\'%s\',\'%s\')' %
                   (m.group(3), s[0], s[1], s[2], s[3], s[4]))
open(dst, 'w').write('\n'.join(out) + '\n')
PYEOF
    elif [ -f "$STUB_SRC/utils/errcodes.h" ]; then
        cp "$STUB_SRC/utils/errcodes.h" "$DIR/utils/"
    fi

    # fmgroids.h — PG15/16: from `#define F_xxx` in fmgr.c; PG17+: prefer
    # a borrow from a local install; last resort: empty stub (our sources
    # reference no F_ OIDs).
    if [ -f "$STUB_SRC/utils/fmgroids.h" ] && [ "$V" -ge 17 ]; then
        cp "$STUB_SRC/utils/fmgroids.h" "$DIR/"
    else
        tar xjf "$TAR" -C "$CACHE" --wildcards "*/src/backend/utils/fmgr/fmgr.c" 2>/dev/null
        local FMGR="$(find "$CACHE" -name fmgr.c -path "*${TV}*" | head -1)"
        if [ -n "${FMGR:-}" ] && grep -q '^#define F_' "$FMGR"; then
            { echo "/* syntax-check stub from fmgr.c */"; grep '^#define F_' "$FMGR"; } > "$DIR/utils/fmgroids.h"
        else
            echo "/* syntax-check stub: no F_ OID needed by duckdb_fdw */" > "$DIR/utils/fmgroids.h"
        fi
    fi

    # fmgrprotos.h — only its *existence* matters for utils/builtins.h.
    if [ -f "$STUB_SRC/utils/fmgrprotos.h" ]; then
        cp "$STUB_SRC/utils/fmgrprotos.h" "$DIR/utils/"
    else
        echo "/* stub */" > "$DIR/utils/fmgrprotos.h"
    fi

    # nodes/nodetags.h — the list of T_* node tags.
    #   PG17 and earlier: a full `typedef enum NodeTag { ... } NodeTag;`
    #   PG18: bare member list, wrapped by the skeleton enum in nodes.h
    #        (which #includes nodetags.h inside the enum body).
    # The tag set is collected from every T_* identifier referenced in the
    # tree (values are irrelevant for -fsyntax-only).
    python3 - "$DIR" "$V" "$REPO_ROOT" <<'PYEOF'
import sys, os, re
inc, ver, repo = sys.argv[1], int(sys.argv[2]), sys.argv[3]
tags = set()

def scan_text(text):
    for m in re.finditer(r'typedef\s+struct\s+([A-Za-z_][A-Za-z0-9_]*)', text):
        tags.add('T_' + m.group(1))
    for m in re.finditer(r'\bT_[A-Za-z0-9_]+', text):
        tags.add(m.group(0))

for root, _dirs, files in os.walk(inc):
    for fn in files:
        if not fn.endswith('.h') or fn == 'nodetags.h':
            continue
        scan_text(open(os.path.join(root, fn), encoding='utf-8', errors='ignore').read())
for fn in os.listdir(repo):
    if fn.endswith(('.c', '.h')):
        scan_text(open(os.path.join(repo, fn), encoding='utf-8', errors='ignore').read())

# T_Invalid and T_Node are always part of the enum.
tags.add('T_Invalid')
tags.add('T_Node')
tags.discard('T_')
lines = ['/* syntax-check stub: T_* tags collected from struct typedefs and */',
         '/* T_* references in the include tree and the extension sources. */']
if ver >= 16:
    # PG16+ nodes.h opens `typedef enum NodeTag { T_Invalid = 0,` and
    # #includes nodetags.h *inside* the enum: emit bare members only.
    lines += ['#ifndef NODETAGS_H', '#define NODETAGS_H']
    lines += ['\t%s,' % t for t in sorted(tags) if t != 'T_Invalid']
    lines += ['#endif']
else:
    lines += ['#ifndef NODETAGS_H', '#define NODETAGS_H',
              'typedef enum NodeTag', '{', '\tT_Invalid = 0,']
    rest = sorted(t for t in tags if t != 'T_Invalid')
    lines += ['\t%s = %d,' % (t, i + 1) for i, t in enumerate(rest)]
    lines += ['} NodeTag;', '#endif']
open(os.path.join(inc, 'nodes', 'nodetags.h'), 'w').write('\n'.join(lines) + '\n')
PYEOF

    # storage/lwlocknames.h — enum of the built-in lwlocks.
    tar xjf "$TAR" -C "$CACHE" --wildcards "*/src/backend/storage/lmgr/lwlocknames.txt" 2>/dev/null
    local LWT="$(find "$CACHE" -name lwlocknames.txt -path "*${TV}*" | head -1)"
    if [ -n "${LWT:-}" ]; then
        { echo "/* syntax-check stub from lwlocknames.txt */";
          echo '#ifndef LWLOCKNAMES_H'; echo '#define LWLOCKNAMES_H';
          echo 'enum BuiltinLWLocks'; echo '{'; echo ' LWLOCK_FIRST_LOCK = 0,';
          grep -E '^[A-Z][A-Z0-9_]*$' "$LWT" | sed 's/^/ /';
          echo ' NUM_INDIVIDUAL_LWLOCKS'; echo '};'; echo '#endif'; } > "$DIR/storage/lwlocknames.h"
    elif [ -f "$STUB_SRC/storage/lwlocknames.h" ]; then
        cp "$STUB_SRC/storage/lwlocknames.h" "$DIR/storage/"
    fi

    # catalog/pg_*_d.h — generated per catalog; borrow from a local install
    # (superset is fine: a value mismatch cannot matter for -fsyntax-only).
    if [ -n "${STUB_SRC:-}" ] && ls "$STUB_SRC"/catalog/pg_*_d.h >/dev/null 2>&1; then
        cp "$STUB_SRC"/catalog/pg_*_d.h "$DIR/catalog/"
    else
        echo "ERROR: no local PG install found to borrow catalog/pg_*_d.h from" >&2
        echo "       (install postgresql-server-dev-17, or prepopulate the include tree)" >&2
        return 1
    fi

    # PG18 slimmed utils/syscache.h down to a generated catalog/syscache_ids.h
    # whose enum members are the MAKE_SYSCACHE() calls in the catalog headers.
    if [ "$V" -ge 18 ]; then
        python3 - "$DIR" <<'PYEOF'
import sys, os, re
inc = sys.argv[1]
names = set()
for fn in os.listdir(os.path.join(inc, 'catalog')):
    if not fn.startswith('pg_') or not fn.endswith('.h'): continue
    for line in open(os.path.join(inc, 'catalog', fn), encoding='utf-8'):
        m = re.match(r'\s*MAKE_SYSCACHE\(\s*(\w+)', line)
        if m: names.add(m.group(1))
with open(os.path.join(inc, 'catalog', 'syscache_ids.h'), 'w') as f:
    f.write('/* syntax-check stub generated from MAKE_SYSCACHE() calls */\n')
    f.write('#ifndef SYSCACHE_IDS_H\n#define SYSCACHE_IDS_H\nenum SysCacheIdentifier\n{\n')
    for n in sorted(names): f.write('\t%s,\n' % n)
    f.write('};\n#define SysCacheSize (%s + 1)\n#endif\n' % sorted(names)[-1])
PYEOF
    fi

    # PG18: pg_publication_d.h must carry the PublishGencolsType enum that
    # genbki copies out of the EXPOSE_TO_CLIENT_CODE section of
    # pg_publication.h (genbki.h #undefs that macro, so the in-header copy
    # is invisible to the compiler in a real build as well).
    if [ "$V" -ge 18 ] && grep -q PublishGencolsType "$DIR/catalog/pg_publication.h" 2>/dev/null; then
        python3 - "$DIR" <<'PYEOF'
import sys, os
d = sys.argv[1]
p = os.path.join(d, 'catalog', 'pg_publication.h')
text = open(p, encoding='utf-8').read()
import re
m = re.search(r'#ifdef EXPOSE_TO_CLIENT_CODE\n(.*?)#endif', text, re.S)
enum_block = m.group(1) if m else ''
dp = os.path.join(d, 'catalog', 'pg_publication_d.h')
extra = ''
if enum_block and 'PublishGencolsType' not in open(dp, encoding='utf-8').read():
    extra = enum_block
    with open(dp, 'a') as f: f.write('\n' + extra.strip() + '\n')
PYEOF
    fi
    return 0
}

pgnum() { # PG_VERSION_NUM for a major version (X.0 release number is enough:
    # all our #if tests use >= NNN000 boundaries)
    case "$1" in
        15) echo 150010 ;; 16) echo 160006 ;; 17) echo 170009 ;; 18) echo 180000 ;;
    esac
}

resolve_include_dir() { # $1 = major version -> sets INCLUDE_DIR, echoes it
    local V=$1 VINC
    case "$V" in
        15) VINC=${FDW_PG15_INCLUDE:-} ;;
        16) VINC=${FDW_PG16_INCLUDE:-} ;;
        17) VINC=${FDW_PG17_INCLUDE:-} ;;
        18) VINC=${FDW_PG18_INCLUDE:-} ;;
    esac
    if [ -n "$VINC" ] && [ -d "$VINC" ]; then
        INCLUDE_DIR=$VINC
    elif [ -d "/tmp/pg${V}_include" ] && [ -f "/tmp/pg${V}_include/postgres.h" ]; then
        INCLUDE_DIR=/tmp/pg${V}_include
    elif [ -n "${STUB_SRC:-}" ] && [ -d "$STUB_SRC" ]; then
        local PC
        PC=$(command -v pg_config 2>/dev/null || true)
        if [ -n "$PC" ]; then
            local VERNUM
            VERNUM=$("$PC" --version | grep -o 'PostgreSQL [0-9]*' | awk '{print $2}')
            if [ "${VERNUM:-}" = "$V" ]; then
                INCLUDE_DIR=$("$PC" --includedir-server)
            fi
        fi
    fi
    if [ -z "${INCLUDE_DIR:-}" ] || [ ! -f "${INCLUDE_DIR}/postgres.h" ]; then
        INCLUDE_DIR="$CACHE/include${V}"
        setup_tarball_tree "$V" "$INCLUDE_DIR" || return 1
    fi
    echo "$INCLUDE_DIR"
}

# ---------------- main ----------------

if [ $# -gt 0 ]; then
    VERSIONS="$*"
else
    VERSIONS="15 16 17 18"
fi

OVERALL=0
for V in $VERSIONS; do
    echo "=============================================================="
    echo " PostgreSQL $V"
    echo "=============================================================="
    INC=$(resolve_include_dir "$V") || { echo "  [FAIL] could not set up include tree for PG$V" >&2; OVERALL=1; continue; }
    echo "  include tree: $INC"
    VFAIL=0
    for src in $SOURCES; do
        ERR=$("$CC" -fsyntax-only -I "$INC" -I "$REPO_ROOT" -D_GNU_SOURCE "$REPO_ROOT/$src" 2>&1 | grep -E "error" | head -15)
        if [ -n "$ERR" ]; then
            echo "  [FAIL] $src"
            echo "$ERR" | sed 's/^/         /'
            VFAIL=1
        else
            echo "  [ OK ] $src"
        fi
    done
    [ "$VFAIL" -eq 1 ] && OVERALL=1
done

echo
if [ "$OVERALL" -eq 0 ]; then
    echo "RESULT: PASS (all versions, all files)"
else
    echo "RESULT: FAIL (details above)"
fi
exit "$OVERALL"
